ubuntu-jdk8-tomcat9:
    image: lsoton/ubuntu-jdk8-tomcat9
    container_name: InCOMM-API-Tomcat9
    volumes:
    - '/VARIABLE_ENV:/VARIABLE_ENV'
    ports:
    - '8680:8080'
    - '9883:8443'
    - '8081:80'
    - '4443:443'
    - '1622:22'
